title: Hello, world! I'm David Freeman
description: > Strength and Honor. Shadow and Dust.
permalink: ':title/'
baseurl: "/"
url: "fangyi-chuangcache.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: fangyiJoe
author-img: david-freeman.jpg
about-author: "..."
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: artemsheludko # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
