title: 20160926
description: Strength and Honor. Shadow and Dust.
permalink: ':title/'
baseurl: "/"
url: "csy-fangyi.github.io"
site-twitter: fangyiJoe

author: fangyiJoe
author-img: slam.JPG
about-author: "Strength and Honor. Shadow and Dust."
github: csy-fangyi

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
