title: Hello, world! I'm fangyiJoe
description: Strength and Honor. Shadow and Dust.
permalink: ':title/'
baseurl: "/"
url: "fangyi-chuangcache.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: fangyiJoe
author-img: slam.JPG
about-author: "..."
github: fangyi-chuangcache

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
